### ISSUE TITLE
Todo Model

### ISSUE THREAD

**Issue by benjaminbwright** [benjaminbwright/vintage-todo-list#19]

**Comment by benjaminbwright** [comment]
- [x] Write some seeds
- [x] Write a seed script that creates todos related to user
- [x] Write a model the makes my seeds work
- [x] Write a relationship between users and todos
